# Generated by Django 2.2.4 on 2020-08-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
    ]
