# Generated by Django 2.2.4 on 2020-08-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='favorites',
            field=models.ManyToManyField(related_name='quotes_liked', to='my_app.Users'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_uploaded', to='my_app.Users'),
        ),
    ]
